### PR TITLE
Use Chef::ServerAPI instead of Chef::REST

### PR DESCRIPTION
**Pull request by jeremiahsnapp**
Chef 12.7+ has moved to using Chef::ServerAPI for
internal API calls.

Reference: https://github.com/chef/chef/blob/12.7.2/RELEASE_NOTES.md#chefrest

### CODE REVIEW

**Comment by jeremiahsnapp** [comment]
This fixes https://github.com/chef/knife-reporting/issues/15

**Comment by plemanach** [comment]
Hi, can someone accept this pull request ?

**Comment by tylercloke** [comment]
Long live `Chef::ServerApi`! 👍

**Comment by danielsdeleo** [comment]
Merged after a rebase as 144f83b08093e775d93faf069e2ed64fe9174fc8

**Pull request closed without merging**
